# Generated by Django 3.0.8 on 2020-07-21 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userpay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=10)),
                ('current_plan', models.CharField(choices=[(12, 'Browse+ | 12MBPS'), (20, 'Pace+ | 20MBPS'), (50, 'Quick+ | 50MBPS')], default=12, max_length=100)),
                ('plan_amount', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('document_no', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to=userpay.models.Profile.file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
