# Generated by Django 3.0.8 on 2020-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0002_auto_20200722_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='payment_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('Octomber', 'Octomber'), ('November', 'November'), ('December', 'December')], max_length=10),
        ),
    ]
