# Generated by Django 3.0.8 on 2020-07-29 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0006_profile_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 29, 12, 4, 19, 739105, tzinfo=utc)),
        ),
    ]
