# Generated by Django 3.0.8 on 2020-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0007_auto_20200729_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='due_date',
            field=models.DateField(auto_now=True),
        ),
    ]
