# Generated by Django 3.0.8 on 2020-07-29 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0008_auto_20200729_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='payment_month',
        ),
        migrations.AlterField(
            model_name='profile',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
