# Generated by Django 3.0.8 on 2020-08-18 19:17

from django.db import migrations, models
import userpay.models


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0009_auto_20200729_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_mobile', models.CharField(max_length=13)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='entertainment/')),
            ],
        ),
        migrations.CreateModel(
            name='WebSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='slider/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='document',
        ),
        migrations.AddField(
            model_name='plandetail',
            name='offer_detail',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_back',
            field=models.FileField(blank=True, upload_to=userpay.models.Profile.file_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_front',
            field=models.FileField(blank=True, upload_to=userpay.models.Profile.file_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='due_date',
            field=models.DateField(default=userpay.models.Profile.dueDate),
        ),
    ]
