# Generated by Django 3.0.8 on 2020-08-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0010_auto_20200818_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
