# Generated by Django 3.0.8 on 2020-08-24 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpay', '0013_auto_20200823_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gst',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='GST_No'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserID'),
        ),
    ]
