# Generated by Django 3.0.8 on 2020-08-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0016_auto_20200826_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entertainment',
        ),
        migrations.DeleteModel(
            name='PlanDetailWeb',
        ),
        migrations.RemoveField(
            model_name='plandetail',
            name='photo',
        ),
        migrations.AddField(
            model_name='plandetail',
            name='data_per_month',
            field=models.CharField(default='Unlimited', max_length=10),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='month_detail',
            field=models.CharField(default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='speed_detail',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='title',
            field=models.CharField(default='Base', max_length=20),
        ),
    ]
