# Generated by Django 3.0.8 on 2020-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0021_transactiondetail_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
