# Generated by Django 3.0.8 on 2020-09-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpay', '0022_transactiondetail_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='invoice',
        ),
    ]
